In [1]:
import numpy as np
import matplotlib.pyplot as plt
import awkward as ak
from coffea import hist, processor
import coffea
import uproot
import sys
sys.path.insert(0,"../")
# from corrections import add_pileup_weight

import pickle
import glob

/uscms/home/kkwok/work/LLP/CMSSW_10_6_20/src/llp_analyzer/coffeaenv/lib/python3.7/site-packages/coffea/util.py:154: FutureWarning: In coffea version v0.8.0 (target date: 31 Dec 2022), this will be an error.
(Set coffea.deprecations_as_errors = True to get a stack trace now.)
ImportError: coffea.hist is deprecated
  warnings.warn(message, FutureWarning)

In [35]:
def rename(name):
    if "HNL" in name:
        m = name.split("_")[2].replace("mHNL","").replace("p0","GeV")
        if "rwctau" in name:
            ct = (name.split("_")[-1].replace("rwctau",""))                
        else:
            ct = (name.split("_")[-1].replace("pl",""))
        label = "_".join([m,ct+"mm"])
    elif "WJet" in name:
        label= "WJetsToLNu"
    elif "EGamma" in name:
        label = "EGamma"
    return label

In [55]:
import HNLprocessor.corrections as corrections

xsections = corrections.load_xsection()

# with open('../HNL_histograms_Sept6_ele_all_v2.pickle','rb') as f:        
with open('../HNL_histograms_Nov18_ele_signal.pickle','rb') as f:            
# with open('../HNL_histograms_Nov17_ele_all.pickle','rb') as f:        
    out_e = pickle.load(f)
# with open('../HNL_histograms_Sept6_muons_all_v2.pickle','rb') as f:
with open('../HNL_histograms_Nov18_muons_signal.pickle','rb') as f:
# with open('../HNL_histograms_Nov17_muons_all.pickle','rb') as f:
    out_mu = pickle.load(f)
lumi = 120 ## fb
# lumi = 1./1000 ## fb
# lumi = 0.939 ## fb
    
for k,h in out_e.items():
    if (type(h)!=hist.Hist): continue
    h.scale({ d: lumi for d in h.identifiers("dataset") if d.name in xsections.keys()}, axis="dataset")
for k,h in out_mu.items():
    if (type(h)!=hist.Hist): continue
    h.scale({ d: lumi for d in h.identifiers("dataset") if d.name in xsections.keys()}, axis="dataset")

In [57]:
out_mu["sumw"]

defaultdict_accumulator(float,
                        {'HNL_muonType_mHNL1p0_pl1000': 661343.0,
                         'HNL_muonType_mHNL4p0_pl1000': 659711.0,
                         'HNL_muonType_mHNL4p0_pl100': 662653.0,
                         'HNL_muonType_mHNL2p0_pl10000': 444704.0,
                         'HNL_muonType_mHNL2p0_pl1000': 659584.0,
                         'HNL_muonType_mHNL1p0_pl10000': 496976.0})

In [222]:
h = out_mu['cutflow']
dataList = [a.name for a in h.identifiers("dataset") if "_201" in a.name]
print(dataList)

[]

In [16]:
for d,v in out["accept"].project("gLLP_csc","dataset")[datasets].values('true').items():
    print(d,v[0],v[1])
#     print(d,v[0][1]/v[0].sum())

/uscms/home/kkwok/work/LLP/CMSSW_10_6_20/src/llp_analyzer/coffeaenv/lib/python3.7/site-packages/coffea/hist/hist_tools.py:377: RuntimeWarning: Not all requested indices present in <Cat (name=dataset) instance at 0x7f6b78d4e2d0>
  "Not all requested indices present in %r" % self, RuntimeWarning

In [28]:
out['cutflow'].identifiers("region")

[<StringBin (csc_cutflow) instance at 0x7fb01ef3a690>,
 <StringBin (dt_cutflow) instance at 0x7fb01ef3a710>]

# Cutflow tables functions

In [4]:
from sigfig import round

def getCutFlowArray(h,dataset):
    h_vals = h.integrate("dataset",dataset).values()
    data = np.array([round(float(vals),sigfigs=3) for cut,vals in h_vals.items()])  
    return data
def getCutNames(h,dataset):
    h_vals = h.integrate("dataset",dataset).values()    
    cutnames = [cut[0] for cut,vals in h_vals.items() ]
    return cutnames
def getRelArr(arr,norm=None):
    if norm==None:
        arr_rel = arr[1:]/arr[0]
    else:
        arr_rel = arr[1:]/norm
    arr_rel = ["%.2e"%i for i in arr_rel]    
    return  np.concatenate((["-"],arr_rel))
def getCutEff(arr,norm=None):
    arr_rel = arr[1:]/arr[:-1]
    arr_rel = ["%.3f "%i for i in arr_rel]    
    return  np.concatenate((["-"],arr_rel))
def getSoverB(arr_s,arr_b):
    arr = np.array(arr_s[1:],dtype=float)/np.array(arr_b[1:],dtype=float)
    arr = ['%.2f'%i for i in arr]
    return np.concatenate((["-"],arr))

# Cutflow tables (CSC)

In [31]:
import pandas as pd
h = out_mu['cutflow'].integrate("region",'csc_cutflow')
name= "(4GeV,1m)"
signal = "HNL_muonType_mHNL4p0_pl1000"

# h = out_e['cutflow'].integrate("region",'csc_cutflow')
# name= "(4GeV,1m)"
# signal = "HNL_electronType_mHNL4p0_pl1000"

dataList = [a.name for a in h.identifiers("dataset") if "_201" in a.name]
# print(dataList)

table={}
cutnames          = getCutNames(h,dataList)

table["data"]     =getCutFlowArray(h,dataList)
table["data_cul"] =getRelArr(table['data'])
table["data_rel"] =getCutEff(table['data'])

table[name]=getCutFlowArray(h,signal)[1:]
table[name+"cul"] =getRelArr(table[name])
table[name+"rel"] =getCutEff(table[name])
table[name+"S/B"] =getSoverB(table[name+"rel"],table["data_rel"])

df_abs = pd.DataFrame.from_dict(table,orient="index",columns=cutnames,dtype=str).transpose()

In [33]:
df_abs.to_latex

<bound method NDFrame.to_latex of                       data  data_cul data_rel (4GeV,1m) (4GeV,1m)cul  \
NoSelection    309000000.0         -        -      81.8            -
trigger_mu     250000000.0  8.09e-01   0.809       40.7     4.98e-01
MET            157000000.0  5.08e-01   0.628       28.5     3.48e-01
METfilters     157000000.0  5.08e-01   1.000       28.5     3.48e-01
good_lepton    102000000.0  3.30e-01   0.650       26.2     3.20e-01
n_cls           61200000.0  1.98e-01   0.600       13.3     1.63e-01
dr_lep          17700000.0  5.73e-02   0.289       12.6     1.54e-01
ME11_12_veto     1190000.0  3.85e-03   0.067       8.64     1.06e-01
jetVeto          1070000.0  3.46e-03   0.899       7.93     9.69e-02
muonVeto         1060000.0  3.43e-03   0.991        7.6     9.29e-02
MB1seg_veto      1060000.0  3.43e-03   1.000       7.51     9.18e-02
RB1_veto         1050000.0  3.40e-03   0.991       7.37     9.01e-02
RE12_veto        1040000.0  3.37e-03   0.990       7.27     8.89e-02
IntimeCut         188000.0  6.08e-04   0.181       7.19     8.79e-02
timeSpreadCut     123000.0  3.98e-04   0.654       7.07     8.64e-02
ClusterID           8970.0  2.90e-05   0.073       4.23     5.17e-02

              (4GeV,1m)rel (4GeV,1m)S/B
NoSelection              -            -
trigger_mu          0.498          0.62
MET                 0.700          1.11
METfilters          1.000          1.00
good_lepton         0.919          1.41
n_cls               0.508          0.85
dr_lep              0.947          3.28
ME11_12_veto        0.686         10.24
jetVeto             0.918          1.02
muonVeto            0.958          0.97
MB1seg_veto         0.988          0.99
RB1_veto            0.981          0.99
RE12_veto           0.986          1.00
IntimeCut           0.989          5.46
timeSpreadCut       0.983          1.50
ClusterID           0.598          8.19  >

In [32]:
df_abs

,data,data_cul,data_rel,"(4GeV,1m)","(4GeV,1m)cul","(4GeV,1m)rel","(4GeV,1m)S/B"
NoSelection,309000000.0,-,-,81.8,-,-,-
trigger_mu,250000000.0,8.09e-01,0.809,40.7,4.98e-01,0.498,0.62
MET,157000000.0,5.08e-01,0.628,28.5,3.48e-01,0.700,1.11
METfilters,157000000.0,5.08e-01,1.000,28.5,3.48e-01,1.000,1.00
good_lepton,102000000.0,3.30e-01,0.650,26.2,3.20e-01,0.919,1.41
n_cls,61200000.0,1.98e-01,0.600,13.3,1.63e-01,0.508,0.85
dr_lep,17700000.0,5.73e-02,0.289,12.6,1.54e-01,0.947,3.28
ME11_12_veto,1190000.0,3.85e-03,0.067,8.64,1.06e-01,0.686,10.24
jetVeto,1070000.0,3.46e-03,0.899,7.93,9.69e-02,0.918,1.02
muonVeto,1060000.0,3.43e-03,0.991,7.6,9.29e-02,0.958,0.97
MB1seg_veto,1060000.0,3.43e-03,1.000,7.51,9.18e-02,0.988,0.99
RB1_veto,1050000.0,3.40e-03,0.991,7.37,9.01e-02,0.981,0.99
RE12_veto,1040000.0,3.37e-03,0.990,7.27,8.89e-02,0.986,1.00
IntimeCut,188000.0,6.08e-04,0.181,7.19,8.79e-02,0.989,5.46
timeSpreadCut,123000.0,3.98e-04,0.654,7.07,8.64e-02,0.983,1.50
ClusterID,8970.0,2.90e-05,0.073,4.23,5.17e-02,0.598,8.19

# Cutflow tables (DT)

In [24]:
import pandas as pd
# h = out_mu['cutflow'].integrate("region",'dt_cutflow')
# name= "(4GeV,1m)"
# signal = "HNL_muonType_mHNL4p0_pl1000"

h = out_e['cutflow'].integrate("region",'dt_cutflow')
name= "(4GeV,1m)"
signal = "HNL_electronType_mHNL4p0_pl1000"

dataList = [a.name for a in h.identifiers("dataset") if "_201" in a.name]
print(dataList)

table={}
cutnames          = getCutNames(h,dataList)
cutnames[0]="NoSelection"
table["data"]     =getCutFlowArray(h,dataList)
table["data_cul"] =getRelArr(table['data'])
table["data_rel"] =getCutEff(table['data'])
# name = "Wjet"
# table[name]=getCutFlowArray(h,"WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8")[1:]
# table[name+"rel"] =getCutEff(table[name])

name= "(4GeV,1m)"
table[name]=getCutFlowArray(h,signal)[1:]
table[name+"cul"] =getRelArr(table[name])
table[name+"rel"] =getCutEff(table[name])
table[name+"S/B"] =getSoverB(table[name+"rel"],table["data_rel"])

df_abs = pd.DataFrame.from_dict(table,orient="index",columns=cutnames,dtype=str).transpose()

['EGamma_2016B', 'EGamma_2016C', 'EGamma_2016D', 'EGamma_2016E', 'EGamma_2016F', 'EGamma_2016G', 'EGamma_2016H', 'EGamma_2017B', 'EGamma_2017C', 'EGamma_2017D', 'EGamma_2017E', 'EGamma_2017F', 'EGamma_2018A', 'EGamma_2018B', 'EGamma_2018C', 'EGamma_2018D']

In [25]:
df_abs

,data,data_cul,data_rel,"(4GeV,1m)","(4GeV,1m)cul","(4GeV,1m)rel","(4GeV,1m)S/B"
NoSelection,73900000.0,-,-,93.9,-,-,-
trigger_ele,32300000.0,4.37e-01,0.437,34.6,3.68e-01,0.368,0.84
MET,21100000.0,2.86e-01,0.653,24.5,2.61e-01,0.708,1.08
METfilters,21100000.0,2.86e-01,1.000,24.5,2.61e-01,1.000,1.00
good_lepton,6310000.0,8.54e-02,0.299,15.2,1.62e-01,0.620,2.07
n_cls_dt,1010000.0,1.37e-02,0.160,5.67,6.04e-02,0.373,2.33
dr_lep,954000.0,1.29e-02,0.945,5.64,6.01e-02,0.995,1.05
dt_MB1veto,23200.0,3.14e-04,0.024,3.06,3.26e-02,0.543,22.62
dt_jetVeto,16700.0,2.26e-04,0.720,2.99,3.18e-02,0.977,1.36
dt_muonVeto,16600.0,2.25e-04,0.994,2.99,3.18e-02,1.000,1.01
dt_RPC,12700.0,1.72e-04,0.765,2.95,3.14e-02,0.987,1.29
dt_MB1adj,11600.0,1.57e-04,0.913,2.85,3.04e-02,0.966,1.06
dt_time,2780.0,3.76e-05,0.240,2.81,2.99e-02,0.986,4.11
dt_deadzones,2420.0,3.27e-05,0.871,2.54,2.71e-02,0.904,1.04

# Cut flow table signal

In [ ]:
#    {'HNL_muonType_mHNL1p0_pl10000': 496976.0,
#      'HNL_muonType_mHNL2p0_pl10000_rwctau5000': 444704.0,
#      'HNL_muonType_mHNL4p0_pl1000': 659711.0,
#      'HNL_muonType_mHNL4p0_pl100_rwctau80': 662653.0,
#      'HNL_muonType_mHNL1p0_pl10000_rwctau20000': 496976.0,

In [30]:
import pandas as pd
h = out_mu['cutflow'].integrate("region",'csc_cutflow')

h_e = out_e['cutflow'].integrate("region",'csc_cutflow')

table={}

name= "(4GeV,1m)"
signal = "HNL_electronType_mHNL4p0_pl1000"
cutnames = getCutNames(h,signal)[1:]

table[name]=getCutFlowArray(h,signal)[1:]
table[name+"rel"] =getCutEff(table[name])

name= "(4GeV,1m)"
signal = "HNL_muonType_mHNL2p0_pl10000_rwctau5000"

table[name]=getCutFlowArray(h,signal)[1:]
table[name+"rel"] =getCutEff(table[name])

df_abs = pd.DataFrame.from_dict(table,orient="index",columns=cutnames,dtype=str).transpose()

In [31]:
df_abs

                        Wjet Wjetrel (4GeV,1m) (4GeV,1m)rel    ele  elerel
Acceptance_csc  2290000000.0       -     104.0            -  104.0       -
trigger_mu      1630000000.0  0.712       49.7       0.478    30.6  0.294
MET             1630000000.0  1.000       34.9       0.702    22.2  0.725
METfilters      1470000000.0  0.902       34.8       0.997    22.2  1.000
good_lepton      961000000.0  0.654       31.8       0.914    13.2  0.595
n_cls            362000000.0  0.377       16.2       0.509    5.95  0.451
dr_lep            48000000.0  0.133       15.4       0.951    5.93  0.997
ME11_12_veto      44800000.0  0.933       10.5       0.682    4.21  0.710
jetVeto           44800000.0  1.000       9.63       0.917    3.88  0.922
muonVeto          44600000.0  0.996       9.24       0.960    3.78  0.974
MB1seg_veto       44400000.0  0.996       9.13       0.988    3.72  0.984
RB1_veto           4900000.0  0.110       8.96       0.981    3.66  0.984
IntimeCut          3730000.0  0.761       8.87       0.990    3.61  0.986
timeSpreadCut       746000.0  0.200       8.72       0.983    3.54  0.981
ClusterID               None    None      5.23       0.600    2.06  0.582

In [67]:
import pandas as pd
h = out_mu['cutflow'].integrate("region",'dt_cutflow')

# h = out_e['cutflow'].integrate("region",'csc_cutflow')

table={}

name= "(4GeV,1m)"
signal = "HNL_muonType_mHNL4p0_pl1000"
cutnames = getCutNames(h,signal)

name= "(1GeV,1m)"
signal = "HNL_muonType_mHNL1p0_pl1000"
table[name]=getCutFlowArray(h,signal)
table[name+"rel"] =getCutEff(table[name])
name= "(2GeV,1m)"
signal = "HNL_muonType_mHNL2p0_pl1000"
table[name]=getCutFlowArray(h,signal)
table[name+"rel"] =getCutEff(table[name])

name= "(4GeV,1m)"
signal = "HNL_muonType_mHNL4p0_pl1000"
table[name]=getCutFlowArray(h,signal)
table[name+"rel"] =getCutEff(table[name])

df_abs = pd.DataFrame.from_dict(table,orient="index",columns=cutnames,dtype=str).transpose()

In [68]:
df_abs

,"(1GeV,1m)","(1GeV,1m)rel","(2GeV,1m)","(2GeV,1m)rel","(4GeV,1m)","(4GeV,1m)rel"
NoSelection,1450000.0,-,45300.0,-,1380.0,-
Acceptance_dt,44100.0,0.030,2180.0,0.048,87.4,0.063
trigger_mu,24500.0,0.556,1280.0,0.587,55.2,0.632
MET,16500.0,0.673,868.0,0.678,38.2,0.692
METfilters,16500.0,1.000,866.0,0.998,38.1,0.997
good_lepton,15200.0,0.921,803.0,0.927,35.3,0.927
n_cls_dt,5060.0,0.333,283.0,0.352,15.2,0.431
dr_lep,4520.0,0.893,254.0,0.898,13.9,0.914
dt_MB1veto,2610.0,0.577,146.0,0.575,7.48,0.538
dt_jetVeto,2540.0,0.973,142.0,0.973,7.26,0.971
dt_muonVeto,2520.0,0.992,142.0,1.000,7.22,0.994
dt_RPC,2490.0,0.988,140.0,0.986,7.15,0.990
dt_MB1adj,2410.0,0.968,137.0,0.979,6.95,0.972
dt_time,2390.0,0.992,134.0,0.978,6.87,0.988
dt_deadzones,2170.0,0.908,122.0,0.910,6.21,0.904

In [79]:
import pandas as pd
h = out_e['cutflow'].integrate("region",'dt_cutflow')


table={}

name= "(4GeV,1m)"
signal = "HNL_electronType_mHNL4p0_pl1000"
cutnames = getCutNames(h,signal)

name= "(1GeV,1m)"
signal = "HNL_electronType_mHNL1p0_pl1000"
table[name]=getCutFlowArray(h,signal)
table[name+"rel"] =getCutEff(table[name])
name= "(2GeV,1m)"
signal = "HNL_electronType_mHNL2p0_pl1000"
table[name]=getCutFlowArray(h,signal)
table[name+"rel"] =getCutEff(table[name])

name= "(4GeV,1m)"
signal = "HNL_electronType_mHNL4p0_pl1000"
table[name]=getCutFlowArray(h,signal)
table[name+"rel"] =getCutEff(table[name])

df_abs = pd.DataFrame.from_dict(table,orient="index",columns=cutnames,dtype=str).transpose()

In [80]:
df_abs.to_excel

<bound method NDFrame.to_excel of                (1GeV,1m) (1GeV,1m)rel (2GeV,1m) (2GeV,1m)rel (4GeV,1m)  \
NoSelection    1590000.0            -   49700.0            -    1510.0
Acceptance_dt    47400.0       0.030     2370.0       0.048       93.9
trigger_ele      15700.0       0.331      821.0       0.346       34.6
MET              10900.0       0.694      570.0       0.694       24.5
METfilters       10900.0       1.000      570.0       1.000       24.5
good_lepton       6910.0       0.634      351.0       0.616       15.2
n_cls_dt          1860.0       0.269      101.0       0.288       5.67
dr_lep            1850.0       0.995      101.0       1.000       5.64
dt_MB1veto        1140.0       0.616       56.9       0.563       3.06
dt_jetVeto        1110.0       0.974       55.7       0.979       2.99
dt_muonVeto       1110.0       1.000       55.6       0.998       2.99
dt_RPC            1100.0       0.991       54.8       0.986       2.95
dt_MB1adj         1060.0       0.964       53.1       0.969       2.85
dt_time           1050.0       0.991       52.5       0.989       2.81
dt_deadzones       960.0       0.914       47.9       0.912       2.54

              (4GeV,1m)rel
NoSelection              -
Acceptance_dt       0.062
trigger_ele         0.368
MET                 0.708
METfilters          1.000
good_lepton         0.620
n_cls_dt            0.373
dr_lep              0.995
dt_MB1veto          0.543
dt_jetVeto          0.977
dt_muonVeto         1.000
dt_RPC              0.987
dt_MB1adj           0.966
dt_time             0.986
dt_deadzones        0.904   >

# OLD CODE Below

In [14]:
from sigfig import round
h = out['cutflow'].integrate("region",'csc_cutflow')

datasets = [
#  'HNL_muonType_mHNL4p0_pl1000',
    "HNL_electronType_mHNL4p0_pl1000"
]
table = {}
table_rel = {}
for i,d in enumerate(np.repeat(datasets,2)): 
    h_vals = h.integrate("dataset",d).values()
    cutnames = [cut[0] for cut,vals in h_vals.items()]
    data = np.array([vals for cut,vals in h_vals.items()])
    label= rename(d)    
    acc = data[1]
    data[1] = data[1]/data[0]
    ## even column: divide by acceptance
    if i%2==0:
        table_val = np.insert(data[2:]/acc, 0,data[1])*100
        table[label+"_acc"] = [round(i,sigfigs=3) for i in table_val]               
    else:
    ## odd column: divide by last cut
        table_val = np.insert(data[3:]/data[2:-1], 0,data[2]/acc) #
        table_val = np.insert(table_val, 0,data[1])
        table_val = table_val*100
        table[label+"_rel"] = [round(i,sigfigs=3) for i in table_val]       
#     table[label]= np.round(data)
#     table_rel[label] = np.round(data[1]+data[1:]/data[2:,5)*100    
# print(table)
import pandas as pd
df = pd.DataFrame.from_dict(table,orient="index",columns=cutnames[1:],dtype=float).transpose()

In [22]:
h.integrate("dataset",dataList).values()

{('NoSelection',): array(56294301.),
 ('trigger_ele',): array(24712128.),
 ('MET',): array(16291161.),
 ('METfilters',): array(16270891.),
 ('good_lepton',): array(5182752.),
 ('n_cls_dt',): array(836129.),
 ('dt_MB1veto',): array(20693.),
 ('dt_jetVeto',): array(14662.),
 ('dt_muonVeto',): array(12284.),
 ('dt_RPC',): array(8902.),
 ('dt_MB1adj',): array(8220.),
 ('dt_time',): array(1972.),
 ('dt_deadzones',): array(1714.)}

In [15]:
h.integrate("dataset","HNL_electronType_mHNL4p0_pl1000").values()

{('NoSelection',): array(1765.83852345),
 ('Acceptance_csc',): array(103.86633914),
 ('trigger_ele',): array(30.64992369),
 ('MET',): array(22.24596668),
 ('METfilters',): array(22.24400299),
 ('good_lepton',): array(13.16019213),
 ('n_cls',): array(5.95459364),
 ('ME11_12_veto',): array(4.21632807),
 ('jetVeto',): array(3.88459938),
 ('muonVeto',): array(3.78423397),
 ('MB1seg_veto',): array(3.72953528),
 ('RB1_veto',): array(3.66531954),
 ('IntimeCut',): array(3.61891698),
 ('timeSpreadCut',): array(3.54989064),
 ('ClusterID',): array(2.06989819)}

In [20]:
from sigfig import round
h = out['cutflow'].integrate("region",'dt_cutflow')

datasets = [
 dataList,dataList,dataList
]
table = {}
table_rel = {}
# for i,d in enumerate(np.repeat(datasets,2)): 
for i,d in enumerate(datasets):     
    h_vals = h.integrate("dataset",d).values()
    cutnames = [cut[0] for cut,vals in h_vals.items()]
    data = np.array([vals for cut,vals in h_vals.items()])
    label= "ele"   
    ## even column: abs.
    if i%3==0:    
#         table_val = data[1:]
#         table[label+"_raw"] = [round(i,sigfigs=3) for i in table_val]                       
        table_val = data[1:]/data[0]*100        
        table[label+"_abs"] = [round(i,sigfigs=3) for i in table_val]                       
    if i%3==1:
        table_val = data[1:]/data[0]*100        
        table[label+"_abs"] = [round(i,sigfigs=3) for i in table_val]               
    elif i%3==2:
        table_val = data[1:]/data[0:-1] #
        table_val = table_val*100
        table[label+"_rel"] = [round(i,sigfigs=3) for i in table_val]        
import pandas as pd
df = pd.DataFrame.from_dict(table,orient="index",columns=cutnames[1:],dtype=float).transpose()

In [21]:
df

               ele_abs  ele_rel
trigger_ele   43.90000    43.90
MET           28.90000    65.90
METfilters    28.90000    99.90
good_lepton    9.21000    31.90
n_cls_dt       1.49000    16.10
dt_MB1veto     0.03680     2.47
dt_jetVeto     0.02600    70.90
dt_muonVeto    0.02180    83.80
dt_RPC         0.01580    72.50
dt_MB1adj      0.01460    92.30
dt_time        0.00350    24.00
dt_deadzones   0.00304    86.90

In [349]:
df_cum

            1GeV_100mm  1GeV_10mm  2GeV_10mm  4GeV_1000mm   EGamma  WJetsToLNu
trigger        24.0589    24.0109    24.0328      23.8570  54.1996      5.2042
Nlep>=1        13.7058    13.6865    13.7120      13.4945  13.8676      2.9073
MET             8.4654     6.6268     6.5854       9.1336   9.5585      2.1811
METfilters      8.3017     6.5969     6.5799       9.0615   9.5537      2.1806
n_cls           0.8020     0.3477     0.2794       0.7005   8.2525      2.1024
ME11_12         0.3172     0.0424     0.0299       0.2807   0.5281      0.2657
JetVeto         0.2870     0.0388     0.0260       0.2575   0.4734      0.2423
MuVeto          0.2773     0.0384     0.0260       0.2516   0.4719      0.2418
MB1seg          0.2687     0.0382     0.0260       0.2454   0.4696      0.2408
RB1             0.2646     0.0381     0.0260       0.2411   0.4677      0.2396
Time            0.2329     0.0145     0.0045       0.2066   0.0770      0.0231
TimeSpread      0.2288     0.0133     0.0041       0.2016   0.0435      0.0179
ClusID          0.1249     0.0008     0.0009       0.1221   0.0037      0.0039
dphi_MET        0.1138     0.0008     0.0006       0.1083   0.0027      0.0022
dphi_lep        0.0456     0.0000     0.0000       0.0479   0.0002      0.0005

# N-1 cut flow

In [206]:
h = out['nCluster_n-1']
h = h.project('Nminus1',"dataset")

h.label="Efficiency"
norm = {}

table = {}
table2= {}
datasets = [
    "HNL_electronType_mHNL1p0_pl10",
#     "HNL_electronType_mHNL1p0_pl100",
#     "HNL_electronType_mHNL1p0_pl1000",    
    "HNL_electronType_mHNL2p0_pl10",
#     "HNL_electronType_mHNL2p0_pl1000",
    "HNL_electronType_mHNL4p0_pl100",
#     "HNL_electronType_mHNL4p0_pl1000",  
    "WJetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8",
    "EGamma_2018A"
]
for d,cutflow in h[datasets].values().items():
    name = d[0]
    label=rename(name)
    data = np.round(cutflow/cutflow[1]*100,3)
    data = data[data!=0.0]    
#     print(label,data)
    table[label] = data
    data2 = data[2:]-data[-1]
    table2[label] = data2
    
cols = ["Inclusive","Presel","ME11_12","JetVeto","MuVeto","MB1seg","RB1",
                            "Time","TimeSpread","ClusID","all"]
    
df = pd.DataFrame.from_dict(table,orient="index",columns=cols)
df = df.transpose().sort_index(1)

In [212]:
cols = ["ME11_12","JetVeto","MuVeto","MB1seg","RB1","Time","TimeSpread","ClusID","all"]
    
df = pd.DataFrame.from_dict(table2,orient="index",columns=cols)
df = df.transpose().sort_index(1)

In [213]:
df

            1GeV_10mm  2GeV_10mm  4GeV_100mm  EGamma  WJetsToLNu
ME11_12         0.000      0.108       0.549   0.015       0.015
JetVeto         0.043      0.000       0.087   0.001       0.000
MuVeto          1.867      0.649       3.819   0.650       0.616
MB1seg          0.000      0.000       0.000   0.001       0.000
RB1             0.000      0.000       0.029   0.002       0.004
Time            1.390      1.514       0.723   0.281       2.076
TimeSpread      0.043      0.000       0.058   0.029       0.026
ClusID          3.692      1.135      12.963   0.530       0.715
all             0.000      0.000       0.000   0.000       0.000